In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("raw_data/electricity_access_percent.csv")
df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,Unnamed: 62
0,Aruba,ABW,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,93.354546,93.356292,93.942375,94.255814,94.578262,94.906723,95.238182,95.570145,NaN,NaN
1,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,44.854885,42.700000,43.222019,69.100000,67.259552,89.500000,71.500000,84.137138,NaN,NaN
2,Angola,AGO,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,32.382469,33.514950,34.600000,35.821964,36.990490,32.000000,42.000000,40.520607,NaN,NaN
3,Albania,ALB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN,NaN
4,Andorra,AND,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,XKX,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,98.377060,0.000000,99.430435,99.773651,99.942505,99.993134,100.000000,100.000000,NaN,NaN
260,"Yemen, Rep.",YEM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,61.751400,63.134281,64.532181,65.942101,75.600000,66.100000,70.213905,71.642349,NaN,NaN
261,South Africa,ZAF,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,82.700000,82.900000,84.700000,85.300000,85.400000,86.000000,85.500000,84.200000,NaN,NaN
262,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,23.235649,22.000000,24.328644,24.894667,25.469702,27.900000,31.100000,27.219337,NaN,NaN
263,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,43.369082,36.063057,36.900000,36.728878,37.076813,32.300000,33.700000,38.145138,NaN,NaN

In [3]:
# Menghitung jumlah data yang hilang sebelum dihapus
missing_data_count = df.isnull().sum()
print("Jumlah data yang hilang sebelum dihapus:")
print(missing_data_count)
print("\n")
# Menghitung jumlah data duplikat sebelum dihapus
duplicate_data_count = df.duplicated().sum()
print("Jumlah data duplikat sebelum dihapus: ", duplicate_data_count)

Jumlah data yang hilang sebelum dihapus:
Country Name        0
Country Code        0
Indicator Name      0
Indicator Code      0
1960              264
                 ...
2014                3
2015                3
2016                3
2017              264
Unnamed: 62       264
Length: 63, dtype: int64


Jumlah data duplikat sebelum dihapus:  0

In [4]:
# Mengatasi data yang hilang
clean_electricity_data = df.dropna()
print("Data yang hilang telah dihapus.")
print (clean_electricity_data)
print("\n")
# Menghapus data duplikat
clean_electricity_data = df.drop_duplicates()
print("Data duplikat telah dihapus.")
print(clean_electricity_data)

Data yang hilang telah dihapus.
Empty DataFrame
Columns: [Country Name, Country Code, Indicator Name, Indicator Code, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, Unnamed: 62]
Index: []

[0 rows x 63 columns]
Data duplikat telah dihapus.
     Country Name Country Code                           Indicator Name  \
0           Aruba          ABW  Access to electricity (% of population)
1     Afghanistan          AFG  Access to electricity (% of population)
2          Angola          AGO  Access to electricity (% of population)
3         Albania          ALB  Access to electricity (% of population)
4         Andorra          AND  Access to electricity (% of population)
..            ...          ...                                      ...
259        Kosovo          XKX  Access to electricity (% of population)
260   Yemen, Rep.          YEM  Access to electricity (% of population)
261  South Africa          ZAF  Access to electricity (% of population)
262        Zambia          ZMB  Access to electricity (% of population)
263      Zimbabwe          ZWE  Access to electricity (% of population)

     Indicator Code  1960  1961  1962  1963  1964  1965  ...        2009  \
0    EG.ELC.ACCS.ZS   NaN   NaN   NaN   NaN   NaN   NaN  ...   93.354546
1    EG.ELC.ACCS.ZS   NaN   NaN   NaN   NaN   NaN   NaN  ...   44.854885
2    EG.ELC.ACCS.ZS   NaN   NaN   NaN   NaN   NaN   NaN  ...   32.382469
3    EG.ELC.ACCS.ZS   NaN   NaN   NaN   NaN   NaN   NaN  ...  100.000000
4    EG.ELC.ACCS.ZS   NaN   NaN   NaN   NaN   NaN   NaN  ...  100.000000
..              ...   ...   ...   ...   ...   ...   ...  ...         ...
259  EG.ELC.ACCS.ZS   NaN   NaN   NaN   NaN   NaN   NaN  ...   98.377060
260  EG.ELC.ACCS.ZS   NaN   NaN   NaN   NaN   NaN   NaN  ...   61.751400
261  EG.ELC.ACCS.ZS   NaN   NaN   NaN   NaN   NaN   NaN  ...   82.700000
262  EG.ELC.ACCS.ZS   NaN   NaN   NaN   NaN   NaN   NaN  ...   23.235649
263  EG.ELC.ACCS.ZS   NaN   NaN   NaN   NaN   NaN   NaN  ...   43.369082

           2010        2011        2012        2013        2014        2015  \
0     93.356292   93.942375   94.255814   94.578262   94.906723   95.238182
1     42.700000   43.222019   69.100000   67.259552   89.500000   71.500000
2     33.514950   34.600000   35.821964   36.990490   32.000000   42.000000
3    100.000000  100.000000  100.000000  100.000000  100.000000  100.000000
4    100.000000  100.000000  100.000000  100.000000  100.000000  100.000000
..          ...         ...         ...         ...         ...         ...
259    0.000000   99.430435   99.773651   99.942505   99.993134  100.000000
260   63.134281   64.532181   65.942101   75.600000   66.100000   70.213905
261   82.900000   84.700000   85.300000   85.400000   86.000000   85.500000
262   22.000000   24.328644   24.894667   25.469702   27.900000   31.100000
263   36.063057   36.900000   36.728878   37.076813   32.300000   33.700000

           2016  2017  Unnamed: 62
0     95.570145   NaN          NaN
1     84.137138   NaN          NaN
2     40.520607   NaN          NaN
3    100.000000   NaN          NaN
4    100.000000   NaN          NaN
..          ...   ...          ...
259  100.000000   NaN          NaN
260   71.642349   NaN          NaN
261   84.200000   NaN          NaN
262   27.219337   NaN          NaN
263   38.145138   NaN          NaN

[264 rows x 63 columns]

In [5]:
clean_electricity_data.to_csv("clean_data/cleaned_electricity_data.csv", index=False)
print("Data yang telah dibersihkan disimpan di folder clean_data bernama cleaned_electricity_data.csv")

Data yang telah dibersihkan disimpan di folder clean_data bernama cleaned_electricity_data.csv